version: '3.9'

services:
  backend:
    image: rujalmhn/aiback:1.0
    container_name: aiback-container
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    image: rujalmhn/aifront:1.0
    container_name: aifront-container
    ports:
      - "80:8501"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
